### ISSUE TITLE
"tapioca dsl" errors when ActiveAdmin present

### ISSUE THREAD

**Issue by bessey** [Shopify/tapioca#280]
We're trying to use Tapioca for the first time on a Rails monolith, but have found we cannot run `tapioca dsl`.
```
/usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl/action_controller_helpers.rb:97:in `instance_method': undefined method `env' for class `ActiveAdmin::BaseController' (NameError)
Did you mean?  Nenv
               end
               END
```

I don't think there's any value in attempting to type the metaprogramming madness that is ActiveAdmin, but as far as i can see there is no way to opt-out on a per directory / constant basis, only to opt-in. 

<details>
<summary> Rest of the stack trace</summary>

```
bundler: failed to load command: tapioca (/usr/local/bundle/bin/tapioca)
Traceback (most recent call last):
	49: from /usr/local/bundle/bin/bundle:23:in `<main>'
	48: from /usr/local/bundle/bin/bundle:23:in `load'
	47: from /usr/local/bundle/gems/bundler-2.2.8/exe/bundle:37:in `<top (required)>'
	46: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	45: from /usr/local/bundle/gems/bundler-2.2.8/exe/bundle:49:in `block in <top (required)>'
	44: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/cli.rb:24:in `start'
	43: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	42: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/cli.rb:30:in `dispatch'
	41: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	40: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	39: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	38: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/cli.rb:494:in `exec'
	37: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/cli/exec.rb:28:in `run'
	36: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/cli/exec.rb:63:in `kernel_load'
	35: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/cli/exec.rb:63:in `load'
	34: from /usr/local/bundle/bin/tapioca:23:in `<top (required)>'
	33: from /usr/local/bundle/bin/tapioca:23:in `load'
	32: from /usr/local/bundle/gems/tapioca-0.4.20/exe/tapioca:21:in `<top (required)>'
	31: from /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	30: from /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	29: from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	28: from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	27: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/cli/main.rb:74:in `dsl'
	26: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca.rb:10:in `silence_warnings'
	25: from /usr/local/lib/ruby/2.6.0/rubygems/user_interaction.rb:47:in `use_ui'
	24: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca.rb:11:in `block in silence_warnings'
	23: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/cli/main.rb:75:in `block in dsl'
	22: from /usr/local/bundle/gems/sorbet-runtime-0.5.6366/lib/types/private/methods/_methods.rb:249:in `block in _on_method_added'
	21: from /usr/local/bundle/gems/sorbet-runtime-0.5.6366/lib/types/private/methods/_methods.rb:249:in `call'
	20: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/generator.rb:150:in `build_dsl'
	19: from /usr/local/bundle/gems/sorbet-runtime-0.5.6366/lib/types/private/methods/_methods.rb:249:in `block in _on_method_added'
	18: from /usr/local/bundle/gems/sorbet-runtime-0.5.6366/lib/types/private/methods/_methods.rb:249:in `call'
	17: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl_compiler.rb:47:in `run'
	16: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl_compiler.rb:47:in `each'
	15: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl_compiler.rb:48:in `block in run'
	14: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl_compiler.rb:87:in `rbi_for_constant'
	13: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl_compiler.rb:87:in `each'
	12: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl_compiler.rb:89:in `block in rbi_for_constant'
	11: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl/action_controller_helpers.rb:84:in `decorate'
	10: from /usr/local/bundle/gems/parlour-6.0.0/lib/parlour/rbi_generator/namespace.rb:137:in `path'
	 9: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl/action_controller_helpers.rb:88:in `block in decorate'
	 8: from /usr/local/bundle/gems/parlour-6.0.0/lib/parlour/rbi_generator/namespace.rb:286:in `create_module'
	 7: from /usr/local/bundle/gems/parlour-6.0.0/lib/parlour/rbi_generator/namespace.rb:286:in `new'
	 6: from /usr/local/bundle/gems/parlour-6.0.0/lib/parlour/rbi_generator/module_namespace.rb:32:in `initialize'
	 5: from /usr/local/bundle/gems/parlour-6.0.0/lib/parlour/rbi_generator/namespace.rb:50:in `initialize'
	 4: from /usr/local/bundle/gems/parlour-6.0.0/lib/parlour/rbi_generator/namespace.rb:50:in `yield_self'
	 3: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl/action_controller_helpers.rb:95:in `block (2 levels) in decorate'
	 2: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl/action_controller_helpers.rb:95:in `each'
	 1: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl/action_controller_helpers.rb:97:in `block (3 levels) in decorate'
```

</details>

Removing all references to ActiveAdmin fixes the issue

**Comment by javierjulio** [comment]
Thanks for identifying and submitting a PR! ❤️

**Comment by bessey** [comment]
Hah, brilliant. Feel free to close this issue then as my personal issue is fixed (once AA cut a gem). I will leave open in case you want to track 

>I'll look into making this more resilient against non-existent method definitions.

here

**Comment by mazinesy** [comment]
Hey, we currently hit have an issue because of this and we are waiting for an AA gem cut. Is there any way we can speed that up ? It's been 3 months

**Comment by mazinesy** [comment]
From [grid-next](https://github.com/shopify/grid-next) repo:

So, I tested this by using `activeadmin` with a specific version ([SHA](https://github.com/activeadmin/activeadmin/commit/f375a7b3066f6d1ae63f874dee8bf2c5808a5847#diff-c9717fa07cf605ae612c15af642fd7c237bab01d48470ae8a84e6059644c50ee) of the fix). Unfortunately, `tapioca` still breaks because of some other issue in [inherited_resources v1.13.0](https://github.com/activeadmin/inherited_resources/tree/v1.13.0/). Here's the stacktrace: 
![image](https://user-images.githubusercontent.com/81764152/123121832-7e198180-d413-11eb-8c32-f7fa6585bbc2.png)

From [this search](https://github.com/activeadmin/inherited_resources/search?q=collection_url), I found [this reference](https://github.com/activeadmin/inherited_resources/blob/b7bb90e756d7af11a9bf8d1878dfcc5a271b30a4/app/controllers/inherited_resources/base.rb#L27) which lead to this [bit of code](https://github.com/activeadmin/inherited_resources/blob/b7bb90e756d7af11a9bf8d1878dfcc5a271b30a4/lib/inherited_resources/url_helpers.rb#L126).

**Comment by paracycle** [comment]
Hey @mazinesy, I just had some time to dig into the error you were having with `inherited_resources`. Thanks for the links and the analysis, it really helped.

I think the problem here is that `InheritedResources::Base` controller is not a complete class, since it still does not have the backing methods for the helper methods that it is declaring. But, I also think the intention was that subclasses would have the backing methods defined via the `InheritedResources::UrlHelpers.create_resources_url_helpers!` method call that you've pointed out.

So, my conclusion is that `InheritedResources::Base` should have been an `abstract` controller since it is not fully ready to be instantiated. I will open that as an issue/PR upstream.

In the meanwhile, I think you might be able to workaround this by calling `InheritedResources::Base.abstract!` in an initializer in your application, which should make Tapioca stop trying to generate anything for that class. 

Please let me know if that works for you.

**Comment by Reizar** [comment]
@paracycle I ran into the same issue and unfortunately the suggested fix didn't work.

What I did:
- Changed ActiveAdmin gem to pull from the master branch so it includes your recent fixes. ( that fixed the first issue )

Added:
```ruby
# config/initializers/inherited_resources.rb
InheritedResources::Base.abstract!
```

Ran `tapioca dsl`

Stacktrace from error:
```
Traceback (most recent call last):
	34: from /usr/local/bundle/bin/tapioca:23:in `<main>'
	33: from /usr/local/bundle/bin/tapioca:23:in `load'
	32: from /usr/local/bundle/gems/tapioca-0.4.23/exe/tapioca:23:in `<top (required)>'
	31: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	30: from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	29: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	28: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	27: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/cli/main.rb:74:in `dsl'
	26: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca.rb:10:in `silence_warnings'
	25: from /usr/local/lib/ruby/2.7.0/rubygems/user_interaction.rb:47:in `use_ui'
	24: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca.rb:11:in `block in silence_warnings'
	23: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/cli/main.rb:75:in `block in dsl'
	22: from /usr/local/bundle/gems/sorbet-runtime-0.5.6492/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
	21: from /usr/local/bundle/gems/sorbet-runtime-0.5.6492/lib/types/private/methods/_methods.rb:270:in `bind_call'
	20: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/generator.rb:149:in `build_dsl'
	19: from /usr/local/bundle/gems/sorbet-runtime-0.5.6492/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
	18: from /usr/local/bundle/gems/sorbet-runtime-0.5.6492/lib/types/private/methods/_methods.rb:270:in `bind_call'
	17: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/compilers/dsl_compiler.rb:47:in `run'
	16: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/compilers/dsl_compiler.rb:47:in `each'
	15: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/compilers/dsl_compiler.rb:48:in `block in run'
	14: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/compilers/dsl_compiler.rb:87:in `rbi_for_constant'
	13: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/compilers/dsl_compiler.rb:87:in `each'
	12: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/compilers/dsl_compiler.rb:89:in `block in rbi_for_constant'
	11: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/compilers/dsl/action_controller_helpers.rb:84:in `decorate'
	10: from /usr/local/bundle/gems/parlour-6.0.1/lib/parlour/rbi_generator/namespace.rb:137:in `path'
	 9: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/compilers/dsl/action_controller_helpers.rb:88:in `block in decorate'
	 8: from /usr/local/bundle/gems/parlour-6.0.1/lib/parlour/rbi_generator/namespace.rb:286:in `create_module'
	 7: from /usr/local/bundle/gems/parlour-6.0.1/lib/parlour/rbi_generator/namespace.rb:286:in `new'
	 6: from /usr/local/bundle/gems/parlour-6.0.1/lib/parlour/rbi_generator/module_namespace.rb:32:in `initialize'
	 5: from /usr/local/bundle/gems/parlour-6.0.1/lib/parlour/rbi_generator/namespace.rb:50:in `initialize'
	 4: from /usr/local/bundle/gems/parlour-6.0.1/lib/parlour/rbi_generator/namespace.rb:50:in `yield_self'
	 3: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/compilers/dsl/action_controller_helpers.rb:95:in `block (2 levels) in decorate'
	 2: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/compilers/dsl/action_controller_helpers.rb:95:in `each'
	 1: from /usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/compilers/dsl/action_controller_helpers.rb:97:in `block (3 levels) in decorate'
/usr/local/bundle/gems/tapioca-0.4.23/lib/tapioca/compilers/dsl/action_controller_helpers.rb:97:in `instance_method': undefined method `edit_resource_path' for class `InheritedResources::Base' (NameError)
```

**Comment by mazinesy** [comment]
I feel like every time we'll solve an issue, we'll find a next one that is waiting to be solved. Can we suggest adding `sorbet/tapioca` to the actual `ActiveAdmin` lib ? This way, this kind of problem won't happen again.

**Comment by mazinesy** [comment]
Got the same error as @Reizar 
![image](https://user-images.githubusercontent.com/81764152/126534584-edb33781-0247-4ca4-82b0-182adc5564fd.png)

@paracycle anymore ideas ? I strongly believe that adding sorbet/tapioca to active admin is the real solution to any of the problem we are facing.
